#version: '4'
services:
  usuarios:
    build: ./microUsuarios
    links:
      - db
    ports:
      - "3001:3001"
  productos:
    build: ./microProductos
    links:
      - db
    ports:
      - "3002:3002"
  ordenes:
    build: ./microOrdenes
    links:
      - db
      - usuarios
      - productos
    ports:
      - "3003:3003"
  microweb:
    build: ./microWeb
    links:
      - db
      - usuarios
      - productos
      - ordenes
    ports:
      - "1080:80"
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root 
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
